# Generated by Django 5.0 on 2023-12-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.ImageField(upload_to='autosapp/images')),
                ('tipo', models.CharField(choices=[('auto', 'Autos'), ('pickup-comercial', 'Pickups y Comerciales'), ('suv-crossover', 'SUVs y Crossovers')], max_length=20)),
            ],
        ),
    ]
